language: python
  - "2.7"

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libc6:i386 libgcc1:i386 gcc-4.6-base:i386 libstdc++5:i386 libstdc++6:i386 zip unzip
  - wget https://dl.dropboxusercontent.com/u/76035852/sm-dev.zip
  - unzip sm-dev.zip
  - chmod +x sm-dev/addons/sourcemod/scripting/spcomp
  - sudo pip install -r requirements.txt

script:
  - PATH+=":$PWD/sm-dev/addons/sourcemod/scripting"
  - "python src/smbuilder/test_cases.py"
