sudo: false

language: python
  - "3.4"

addons:
    apt_packages:
        - lib32stdc++6  # needed for spcomp
        - elinks

env:
    - SMVERSION=1.8

install:
    # install smbuilder
    - pip install --user -r requirements.txt
    - python setup.py install --prefix=~/.local

    # install the sourcemod compiler
    - SMPACKAGE="http://sourcemod.net/latest.php?os=linux&version=${SMVERSION}"
    - wget $SMPACKAGE
    - tar xfz $(basename $SMPACKAGE)
    - cd addons/sourcemod/scripting/
    - chmod +x spcomp
    - PATH+=":$PWD"
    - cd ../../..

script:
  - "python src/smbuilder/test_cases.py"
